name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the feature
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem does this feature address?
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe how you think this should work
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: additional
    attributes:
      label: Additional context
